### ISSUE TITLE
Auto apply codes

### ISSUE THREAD

**Issue by rockydares** [Noobita69/HomeMiniGen#1]
Without auto applying these codes, this script is no use. I tried entering 50 codes manually, no luck. Please make a pyautogui script that takes each codes saved from codes.txt and pastes on that Flipkart page, if code doesn't match, it clicks 'Redeem another voucher' and goes on.

**Comment by Mr-HotHead** [comment]
> Without auto applying these codes, this script is no use. I tried entering 50 codes manually, no luck. Please make a pyautogui script that takes each codes saved from codes.txt and pastes on that Flipkart page, if code doesn't match, it clicks 'Redeem another voucher' and goes on.

The only way to check those codes are by seeing whether they are redeemed successfully or not. If they are redeemed then it means that it is a real code,but you cant use it again cause just now it is redeemed,and even to check many codes you need many flipkart accounts,cause they wont accept many codes for to redeem. Even if they allow to redeem,they will cancel they order saying you used many codes,and even they will block your IP if you check many codes.

**Comment by harshakshit** [comment]
Did you get any working code for yourself?

**Comment by rockydares** [comment]
> Did you get any working code for yourself?

No, I couldn't find one.
